name: flutter_anycam
description: "Plugin Flutter para captura e análise de frames de múltiplos tipos de câmera (frontal, traseira, USB e RTSP), com suporte a conversão de frames para JPEG e processamento em tempo real."
version: 1.0.8
homepage: https://github.com/michaelopes/flutter_anycam

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: br.dev.michaellopes.flutter_anycam
        pluginClass: FlutterAnycamPlugin
      ios:
        pluginClass: FlutterAnycamPlugin

