name: flutter_anycam
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/michaelopes/flutter_anycam

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  imagekit_ffi: ^0.0.4
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: br.dev.michaellopes.flutter_anycam
        pluginClass: FlutterAnycamPlugin
      ios:
        pluginClass: FlutterAnycamPlugin

